sudo: required
env:
  global:
    - NODE_OPTIONS="--dns-result-order=ipv4first"

 
services:
  - docker

 
script:
  - docker --version
  - docker build -t algofields/node .
  - docker images algofields/node