sudo: required
env:
  global:
    - NODE_OPTIONS="--dns-result-order=ipv4first"

services:
  - docker

script:
  - docker build --ulimit nofile=65536:65536 --security-opt seccomp=unconfined -t algofields/node .
  - docker images algofields/node