sudo: required
env:
  global:
    - NODE_OPTIONS="--dns-result-order=ipv4first"

before_install:
  - sudo systemctl stop docker.service && sudo systemctl stop docker.socket
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - yes | sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  
services:
  - docker

script:
  - docker build -t algofields/node .
  - docker images algofields/node